### ISSUE TITLE
-Werror=unused-variable -Wespressif=lets-break-everyones-library

### ISSUE THREAD

**Issue by tobozo** [vortigont/esp32-flashz#4]
Hi!

got this error treated as a warning while running a compilation CI test with compilation warnings set to `all`.

```log
  /home/runner/Arduino/libraries/esp32-flashz/src/flashz.cpp: In member function 'size_t FlashZ::writezStream(Stream&, size_t)':
  /home/runner/Arduino/libraries/esp32-flashz/src/flashz.cpp:307:9: error: unused variable 'err' [-Werror=unused-variable]
       int err = deco.inflate_stream_to_cb(data, len, [this](size_t i, const uint8_t* d, size_t s, bool f) -> int { return flash_cb(i, d, s, f); });
           ^~~
  cc1plus: some warnings being treated as errors
```

there are several ways this can be fixed:

- by setting compiler warnings to `default` (which I obviously did in my CI script)
- by ignoring the warning, either before I include esp32-flashz, or by modifying esp32-flashz.cpp:

```cpp
#pragma GCC diagnostic ignored "-Wunused-variable"
```

- by modifying esp32-flashz.cpp and actually using `err` in the unit:

```cpp
if( err ) {
   // do something
}
```

**Comment by vortigont** [comment]
tnx @tobozo 
yeah, I had an intention to handle the error for `writeStreamz()` initially. But since this func usually runs asynchronously, it need an external callback handler of a kind. Hope to implement it someday :)
Will since it for now but let's keep it to remind me about my duties :)
