### ISSUE TITLE
Error: Not Enough Space!

### ISSUE THREAD

**Issue by luisfear** [vortigont/esp32-flashz#6]
Hello, 
I have an error when running the update and I don't know how to solve it.

My uncompressed code version is able to update a 1048 KB BIN, but when I try the esp32-flashz version with the same BIN compressed to 633 KB I always get the following error when I am about 60% of the way through the download:

**[139062][E][flashz.cpp:294] flash_cb(): [FLASHZ] ERROR, flashed 0 of 32768 bytes chunk, err: Not Enough Space!
[139062][E][flashz.cpp:263] writez(): [FLASHZ] Inflate ERROR: -1**

I'm using ESP32 and I'm writing with FlashZ::getInstance().writez(const uint8_t *data, size_t len, bool final)

Can you help me?

**Comment by luisfear** [comment]
Thank you very much, exactly that was the problem and now it is solved. 
Excellent work

**Comment by capedra** [comment]
@luisfear 
@vortigont 
Wow, I also just had this same issue a few moments ago and the solution was to ```beginz``` with ```UPDATE_SIZE_UNKNOWN```.
Congratulations and Thanks for your great library, @vortigont  !!

**Comment by capedra** [comment]
@vortigont How may we make the ```onProgress``` function to work? Thanks again!
